# Site settings
title: zachmoshe.com
about_me: Technical Consultant for Risk Management, Fraud Prevention and Data Science
description: All about data, data mining and new technologies experiments
keywords: machine-learning,deep-learning,data-science,data,technology
quote:
  text: Computers are useless. They can only give you answers.
  by: Pablo Picasso, 1960s
  url: http://en.wikiquote.org/wiki/Pablo_Picasso#1960s
url: http://zachmoshe.com
baseurl: '/'
google_analytics: UA-54835912-3
disqus_shortname: zachmoshe

author:
  name: 'Zach Moshe'
  email: zachmoshe@gmail.com
  twitter_username: zachmoshe
  facebook_username: zach.moshe
  github_username: zachmoshe
  linkedin_username: zachmoshe
  stackoverflow_username: zach-moshe
  stackoverflow_userid: 1643257

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: :year/:month/:day/:title.html
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
#markdown: kramdown

#kramdown:
  # use Github Flavored Markdown
  #input: GFM
  # do not replace newlines by <br>s
  #hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['LICENSE', 'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'bin']
